$ANSIBLE_VAULT;1.1;AES256
34336262323161616562643062303533383865613438333934316562363532326535656137626262
3263613162636636653539366265633736663062643561300a323564383166343130623435303539
37643365333366613436353963306333326336386364643832653364643363356131663633623466
6162306635323465300a623032616665653934613738386336313139343333666239363964616363
30373063343933393263663865646361346637626534636364303538646531353133633333663566
39303130393132653435663930636637303838396330356563306237386139303664666437313635
32633531616266383461636265373733306339643761333839396135656234346136653335343035
32633761326635393636366133393238623133383830393361666636633339376165653231646234
34333464323562616464666639303935623863636261653332326662373263653938383232393837
66386531633566306464346162396664313261336638306661343333303836646337626533326531
36633237373233666264653935653037363539656538346138623739313439373436373130356164
30633661333034376236346433313366326330663239393461336531366464343131633864363833
37666134623636616232376438363533306434346363656266323338353337333433366130616164
63333561383366636661313137356435316639363034653461616564346562336136356261353032
35636533306463626639353735343463306533653164323063663365626565636636343432393239
39663337656361613531613165313137333939376162623434383266396239336635313762626132
61373564303537383732653961313430343363376562653231663065656162363866373330356138
32336265633263633832666264613761643437373138656166663364646661313237613131636637
66333336616261633665616531313737613763386234316338316134303664363737396536363937
33636633616636643163366561323938303830323066636138353165393331383036633036316437
31616661373965393938613766386639613335313664313461353332656365666533623162336337
36336235643333363935666564363263623965353239326637366538353964353536613636333930
62623966663337396563326234333137366631353233363736656531393064353861376364333464
33303839393530336637
