- name: Ensure /opt/stack directory exists
  file:
    path: /opt/stack
    state: directory

- name: Generate docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/stack/docker-compose.yml

- name: Launch stack containers
  become: true
  shell: docker-compose up -d
  args:
    chdir: /opt/stack

- name: Stop and remove all containers and volumes
  become: true
  shell: docker-compose -f /opt/stack/docker-compose.yml down
  tags: [down]

- name: Stop and remove all containers and volumes
  become: true
  shell: docker-compose -f /opt/stack/docker-compose.yml down -v
  tags: [clean]

